/**
 * otpAttempts — client-side failed-OTP tracking, keyed per e-mail address.
 *
 * UX-level deterrence ONLY (Route A, see manual/MAINTENANCE.md §3.6): the
 * e-mailed token is generated by GoTrue, so the 5-attempt limit cannot be
 * enforced by us server-side — this guards against typo loops and must never
 * be treated as a security boundary. Supabase applies its own rate limits
 * (1 OTP request / 60 s per user) and expiry on the real endpoint.
 *
 * Backing store: localStorage in the browser; `setOtpStoreForTesting()`
 * injects a Map-backed fake so the logic is unit-testable under plain node.
 */

export const MAX_ATTEMPTS = 5
/** Failed attempts older than this stop counting (natural decay). */
const LOCK_WINDOW_MS = 15 * 60 * 1000 // 15 minutes

export interface OtpAttemptState {
  /** Failed verify attempts counted in the current window. */
  fails: number
  /** Remaining attempts before lock (>= 0). */
  attemptsLeft: number
  /** True once MAX_ATTEMPTS failures were registered (until reset). */
  locked: boolean
}

interface AttemptEntry {
  fails: number
  lastFail: number
}

type OtpStore = {
  getItem(key: string): string | null
  setItem(key: string, value: string): void
  removeItem(key: string): void
}

const STORAGE_KEY = 'verbologic-otp-attempts'

let storeOverride: OtpStore | null | undefined

/** Test seam: inject a fake store (or null) instead of localStorage. */
export function setOtpStoreForTesting(s: OtpStore | null): void {
  storeOverride = s
}

function backing(): OtpStore | null {
  if (storeOverride !== undefined) return storeOverride
  return import.meta.client ? localStorage : null
}

function readAll(): Record<string, AttemptEntry> {
  const raw = backing()?.getItem(STORAGE_KEY) ?? null
  if (!raw) return {}
  try {
    return JSON.parse(raw) as Record<string, AttemptEntry>
  } catch {
    return {}
  }
}

function writeAll(all: Record<string, AttemptEntry>): void {
  const s = backing()
  if (!s) return
  s.setItem(STORAGE_KEY, JSON.stringify(all))
}

function entryFor(all: Record<string, AttemptEntry>, key: string): AttemptEntry {
  const entry = all[key] ?? { fails: 0, lastFail: 0 }
  // Old failures decay out of the window.
  return Date.now() - entry.lastFail > LOCK_WINDOW_MS ? { fails: 0, lastFail: 0 } : entry
}

function toState(entry: AttemptEntry): OtpAttemptState {
  return {
    fails: entry.fails,
    attemptsLeft: Math.max(0, MAX_ATTEMPTS - entry.fails),
    locked: entry.fails >= MAX_ATTEMPTS
  }
}

/** Current attempt state for an e-mail. */
export function otpState(email: string): OtpAttemptState {
  const key = email.trim().toLowerCase()
  if (!key) return { fails: 0, attemptsLeft: MAX_ATTEMPTS, locked: false }
  return toState(entryFor(readAll(), key))
}

/** Register one failed verify; returns the updated state (may lock). */
export function registerOtpFailure(email: string): OtpAttemptState {
  const key = email.trim().toLowerCase()
  if (!key) return { fails: 0, attemptsLeft: MAX_ATTEMPTS, locked: false }
  const all = readAll()
  const entry = entryFor(all, key)
  entry.fails += 1
  entry.lastFail = Date.now()
  all[key] = entry
  writeAll(all)
  return toState(entry)
}

/** Clear the counter — called when a fresh code is requested. */
export function clearOtpAttempts(email: string): void {
  const key = email.trim().toLowerCase()
  if (!key) return
  const all = readAll()
  delete all[key]
  writeAll(all)
}

/** Normalise pasted/typed input to at most 6 digits: '123 456' → '123456'. */
export function normalizeOtp(raw: string): string {
  return raw.replace(/\D/g, '').slice(0, 6)
}

/** Display grouping: '123456' → '123 456' (two groups of three). */
export function formatOtp(digits: string): string {
  const d = normalizeOtp(digits)
  return d.length > 3 ? `${d.slice(0, 3)} ${d.slice(3)}` : d
}

/** True when the input is exactly 6 digits (format gate before submitting). */
export function isWellFormedOtp(input: string): boolean {
  return /^\d{6}$/.test(normalizeOtp(input))
}
