import { fileURLToPath } from 'node:url'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2026-09-09',
  devtools: { enabled: true },

  // Full static-site generation: `nuxt generate` pre-renders every route.
  ssr: true,
  nitro: {
    prerender: {
      routes: ['/']
    }
  },

  // Source lives under src/ (app.vue, pages, components, stores, lib) — content/ and
  // public/ remain at the repo root per the decoupled O(N) architecture.
  srcDir: 'src/',
  dir: {
    // Absolute path keeps public/ at the repo root even with a custom srcDir.
    public: fileURLToPath(new URL('./public', import.meta.url))
  },

  // Supabase — public values baked into the static bundle at build time.
  // Set via NUXT_PUBLIC_SUPABASE_URL / NUXT_PUBLIC_SUPABASE_ANON_KEY (.env,
  // Cloudflare Workers Builds). Empty defaults keep `nuxt generate` green
  // without credentials; supabase.client.ts then no-ops gracefully.
  runtimeConfig: {
    public: {
      supabaseUrl: '',
      supabaseAnonKey: ''
    }
  },

  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      title: 'Verbologic — Foreign Language Learning',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content:
            'An enterprise-grade, decoupled platform for foreign language learning with instant client-side search.'
        }
      ],
      // Google Fonts — typography system, see src/assets/css/tailwind.css.
      // display=swap avoids invisible text while webfonts load; each family's
      // cyrillic (RU) and latin-ext (HU 'ő'/'ű') subsets are served on demand
      // via unicode-range @font-face blocks in the css2 response.
      link: [
        // Favicon set — generated by scripts/generate-logos.py into public/.
        // The .ico fallback comes first; the adaptive .svg (embedded
        // prefers-color-scheme media query) upgrades Chromium/Firefox tabs.
        { rel: 'icon', type: 'image/x-icon', sizes: '16x16 32x32 48x48', href: '/favicon.ico' },
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Plus+Jakarta+Sans:wght@600&family=Space+Grotesk:wght@700&display=swap'
        }
      ]
    }
  },

  modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss'],

  // Tailwind entrypoint — utility-first styling for all components.
  css: [
    '~/assets/css/tailwind.css',
    '~/assets/css/themes.css',
    '~/assets/css/layout.css'
  ]
})
